### ISSUE TITLE
reduce boilerplate with connecting a component to ResponsiveStore?

### ISSUE THREAD

**Issue by mondomishi** [aaivazis/alt-responsive#5]
Should we expose a decorator which reduces the boilerplate involved with making a view responsive?

Here's the boilerplate to avoid:

``` js
import React from 'react'
import connectToStores from 'alt/utils/connectToStores'
import ResponsiveStore from 'stores/ResponsiveStore'

@connectToStores
class MyComponent extends React.Component {
    static getStores() {
        return [ResponsiveStore]
    }

    static getPropsFromStores() {
        return ResponsiveStore.getState()
    }

    // ...
}
```

Here's some sample usage with the proposed decorator:

``` js
import React from 'react'
import {responsive} from 'alt-responsive'
import ResponsiveStore from 'stores/ResponsiveStore'

@responsive(ResponsiveStore)
class MyComponent extends React.Component {
    // ...
}
```

Essentially this decorator would provide a quick way to have a view listen to **any** single (or multiple if you want to implement it that way) store (note that it does not need to be the `ResponsiveStore`).

Pros:
- quick
- easy
- since it is likely that many components will want to be responsive, quick and easy are somewhat important pros

Cons:
- not explicit about how the component is getting its props
- forces the component to receive **all** the props from the store
- is it really that much quicker?

**Comment by AlecAivazis** [comment]
Following our discussion, I think we agree that this sort of behavior belongs built into the connectToStores (or some other alt decorator) so I am going to close this
